### PR TITLE
style: Update texts/design of course upgrade card

### PR DESCRIPTION
**Pull request by arslanashraf7**
#### Related ticket:
https://github.com/mitodl/mitxonline/issues/556

#### What this PR does?
- Updates the style of the course upgrade card as per required in MITxOnline
- Adds configuration values to set the text for the title and description
- Updates the card code to use the text from the environment
- Updates the Upgrade button text to skip showing price

#### How should this PR be tested?
- Setup your edX devstack to use this branch for `frontend-app-learning` (You could simply add this fork's remote and checkout this branch)
- Do a `make frontend-app-learning-shell`, in the shell run npm run build
- Restart your MFE container `docker-compose restart frontend-app-learning`
- To see the upgrade dialog you need to set up a few things mentioned in https://github.com/mitodl/mitxonline/issues/567#issuecomment-1131656687
- Set title/description environment values want to see in the `.env.development` file 
- Once you land on the course details page you should be able to see the updated changes
- Once above is done:
    - You should see the updated card title
    - You should see the updated card descriotion
    - You should see the `Upgrade` text only in the Upgrade button (That used to be `Upgrade for $149` etc)

#### Screenshot 
**Desktop**
Screenshot 2022-05-31 at 2 49 28 PM

**Mobile**
Screenshot 2022-05-31 at 2 49 39 PM

### CODE REVIEW

**Comment by arslanashraf7** [comment]
@rhysyngsun I've made the title & description values configurable so that we can change them whenever we want. 
In addition, I didn't create a PR to set up the values in `ol-infrastructure` before the PR is approved, so if we are good with this approach we'd need to create a PR to set the texts that we want. As of now, we need to finalize what text we want to display in place of the course upgrade card's title & description.

**Comment by briangrossman** [comment]
@rhysyngsun and @arslanashraf7 

I just wanted to call attention to this comment while we're working on this:
https://github.com/mitodl/mitxonline/issues/539#issuecomment-1139000143

Given that we have flexible pricing, we probably want to make the text on the button customizable. 

It might make more sense to just say `Upgrade`?

**Comment by pdpinch** [comment]
> It might make more sense to just say Upgrade?

Yes please!

**Comment by arslanashraf7** [comment]
So in response to the above comments, I've updated the PR to show only `Upgrade` text for the upgrade button that previously used to be `Upgrade for $149(Course Price)`. Also, I updated the screenshots in the PR description.

I didn't introduce environment-specific value for this unlike description/title texts for the card because the probability of changing this feels rare to me.

In addition, I've just trimmed the price from the places where it shows, although we will still need to set the price for Course Modes to show the card, but now the price won't show on the frontend.

**Comment by pdpinch** [comment]
I could be wrong, but I don't think there's much value to making the title and message configurable. And, in my experience, it's seems pretty hard for us to manage all these variables. 

But... I'm looking for the final text for this page and I can't find it. I'll try to track that down asap.

**Comment by arslanashraf7** [comment]
What you are saying is valid as well and I agree keeping the config settings gives us flexibility but adds some difficulty to manage (Not to mention that would require a PR in ol-Infrastructure too). If the probability of these texts changing is low/none we can just hardcode the strings. That would be simpler than keeping the configs.

I'll update the PR accordingly once the text is finalized.

**Comment by rhysyngsun** [comment]
@arslanashraf7 I realized today that we actually aren't currently using this fork of the MFE, which lead me down the path of realizing that since we currently build this MFE off of openedx's `master` branch this raises a few issues:

- We'd need to have automation around continuously rebasing this fork and deploying that instead
- These rebases would be subject to merge conflicts, which means the deployment would break until manual intervention
- A deployment not going out could cause the deployed application to break if for example there was a breaking change to `edx-platform`

I talked to Tobias and he agreed we'd end up dealing with these problems, so I spent some time digging into a different way to deal with this and I realized that the code that you're changing here is actually the default value for an i18n string. It looks like the MFE doesn't support the `en` locale directly but instead expects the default strings.

So I'm wondering if a better approach would be to use an `en.json`. This would let us store our own customizations for translations (including english) somewhere else and at build time run a merge with those and the upstream ones prior to compiling the MFE app. This would mean we wouldn't have to fork this for a wording change. It's also the same strategy that `tutor` uses: https://github.com/overhangio/tutor-mfe/blob/master/tutormfe/templates/mfe/build/mfe/i18n/i18n-merge.js

So could you see about seeing if OpenedX would be open to having an upstream change done to introduce an `en.json` file? It could probably be an empty one so that they could continue to use the `default` argument as where they define those upstream. There might be other complications upstream that I'm not aware of but hopefully you can talk to the openedx devs to sort it out.

**Comment by arslanashraf7** [comment]
@rhysyngsun I agree this could become hard and I also thought of a similar alternate in [This comment](https://github.com/mitodl/mitxonline/issues/556#issuecomment-1132883358) of `en.json`.
In our case there were some style customizations e.g. centered `Upgrade today!`, and yellow background and removal of the price itself from the text of the upgrade button.

In addition, I heard that the edX team was planning on working out a solution on theming MFEs overall and I could find some relevant links that relate to that e.g. [A discussion post](https://discuss.openedx.org/t/theming-branding-for-mfes/7386), [Brand customization proposal](https://open-edx-proposals.readthedocs.io/en/latest/architectural-decisions/oep-0048-brand-customization.html) & [edX's Brand's repo](https://github.com/openedx/brand-openedx) itself. 

But intend to look more and discuss this with someone working on the MFEs for our solution.

**Comment by rhysyngsun** [comment]
@arslanashraf7 thanks! It would also be good to get an idea from them in terms of the timing of when they'd be doing this and if that ends up being too far out (e.g. more than a month I'd say), whether they're open to a short term solution like the one I suggested above?

**Comment by pdpinch** [comment]
I was able to locate the final text: 

> Upgrade your course today

> You are taking the free version of this course. Upgrade today and, upon passing, receive your digital certificate signed by MIT faculty to to highlight the knowledge and skills you’ve gained from this MITx course.

**Comment by arslanashraf7** [comment]
@rhysyngsun We have had a response from the Frontend working group of edX on our above solution and post edX discussion board [here](https://discuss.openedx.org/t/override-the-messages-in-mfes/6769/4).

I haven't dug much into the details of those things yet but initially, it looks like this solution in the MFE might not be the right place and even moving those to the brands edx app will bring some caveats because the brand's package serves as common for platform and MFEs.

 I didn't see any exact estimates on when they plan to do it but think that's going to take a lot more than a month. With the reservations pointed out there I think upstreaming something like this will have a hard time since the change they are looking at will be platform wide.

However, Could you also take a look at [this comment](https://discuss.openedx.org/t/override-the-messages-in-mfes/6769/4) and probably share your thoughts.

**Comment by rhysyngsun** [comment]
@arslanashraf7 thanks for having those conversations with them. I talked to @pdpinch about this and based on their responses that means we still have to do a fork. So I think the best way to go about this is to minimize the footprint of the changes we make, which I think means we should add the `en.json` I mentioned above, plus an import for it to `i18n/index.jsx`. Since this amounts to a 2-line change (plus adding `en.json`, although it sounds like they simply wouldn't be doing this anytime soon if at all), that keeps the chances for a conflict pretty low since it'd only happen if they add a language that falls alphabetically immediately after `ca.json`.

We'll also need to update the deployment scripts to use this build and also continuously rebase off the upstream, I'll talk to Tobias about that.

**Comment by arslanashraf7** [comment]
@rhysyngsun I agree with keeping the footprint low enough to keep this from conflicts.

> I mentioned above, plus an import for it to i18n/index.jsx. Since this amounts to a 2-line change (plus adding en.json

This seems right to me as well and I tried it as well. Plus, I agree not to change HTML/JS code within the MFE.

However, We'll need to get some tweaks([as seen in the screenshot here](https://github.com/mitodl/mitxonline/issues/556#issue-1232743323)) done on the required design since we won't be touching the HTML/JS. Those tweaks would be as follows:

1) There is yellow background + centered text for `Upgrade your course today` title in the ticket design. (Since we won't change HTML/CSS so in this case it would be left-aligned without yellow background). Is this fine?
2) In the original card design there are bullets [added through React component]s(https://github.com/mitodl/frontend-app-learning/blob/master/src/generic/upgrade-notification/UpgradeNotification.jsx#L16-L23). (So can we divide our description text into bullets?) 

The above questions looks flexible enough to me but, Maybe @pdpinch might answer better?

Here is the screenshots of the original edX based design that would help for the above points.

Screenshot 2022-06-17 at 6 10 50 PM

**Comment by rhysyngsun** [comment]
@arslanashraf7 I think this can be closed now?

**Comment by arslanashraf7** [comment]
> @arslanashraf7 I think this can be closed now?

Yes, Closing this PR in favor of https://github.com/mitodl/frontend-app-learning/pull/3.

**Pull request closed without merging**
